steps:

  # install dependencies for angular app
  - name: "gcr.io/cloud-builders/npm:node-14.15.0"
    args: ["install"]

  # build production ready frontend angular app
  - name: "gcr.io/cloud-builders/npm:node-14.15.0"
    args: ["run", "build", "--prod"]

  # deploy to google cloud app engine
  - name: "gcr.io/cloud-builders/npm:node-14.15.0"
    args: ["app", "deploy", "--version=prod"]
