steps:
 # install dependencies for angular app
  - name: node:14.15.0
    entrypoint: npm
    args: ["install"]

  # build production ready frontend angular app
  - name: node:14.15.0
    entrypoint: npm
    args: ["run", "build", "--prod"]

  # deploy to google cloud app engine
  - name: gcloud
    args: ["app", "deploy", "--version=prod"]
